# Generated by Django 4.1 on 2022-08-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Codigo producto"
                    ),
                ),
                ("nombre", models.CharField(max_length=20, verbose_name="Nombre")),
                ("marca", models.CharField(max_length=20, verbose_name="Marca")),
                (
                    "descripcion",
                    models.TextField(max_length=200, verbose_name="Descripcion"),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Precio"
                    ),
                ),
                ("stock", models.PositiveSmallIntegerField(verbose_name="Stock")),
            ],
            options={
                "verbose_name_plural": "Productos",
                "ordering": ["nombre", "marca", "precio"],
            },
        ),
    ]
