# Generated by Django 4.1 on 2022-08-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(
                blank=True, max_length=200, verbose_name="Descripcion"
            ),
        ),
    ]
